frontend/config/routes.rb
class UrlConstraint 
    def matches?(request) 

      unless request.params[:cms_id].blank?
        if check_path(request.params[:cms_id]) 
          current_store = amz_current_store(request) 
          found = Amz::Cms.exists_by_friendly_id?(store_id: current_store.id, slug: request.params[:cms_id] ) 
        end
      end
      unless request.params[:taxon_id].blank?
        if check_path(request.params[:taxon_id])
          current_store = amz_current_store(request)
          # taxons = current_store.taxons 
          # found = taxons.friendly.exists_by_friendly_id?(request.params[:taxon_id]) 
          found = Amz::Taxon.exists_by_friendly_id?(store_id: current_store.id , permalink: request.params[:taxon_id] )
        end
      end  
      unless request.params[:review_id].blank? 
        if check_path(request.params[:review_id])
          # current_store = amz_current_store(request)
          # reviews = current_store.reviews 
          # found = reviews.friendly.exists_by_friendly_id?(request.params[:review_id])  
          found = Amz::Review.exists_by_friendly_id?(request.params[:review_id])  
        end 
      end  
      unless request.params[:unmatched_route].blank? 
        found = check_path(request.params[:unmatched_route])
      end

      found   
    end

    def amz_current_store(request) 
      Amz::Store.current(request.env['SERVER_NAME']) 
    end

    def check_path(path)
      if (path.include?('active_storage')|| path.match(/^\/?admin/) || path.include?('admin/')  || path.include?('sidekiq') || path.include?('ckeditor') )  
        found = false 
      else 
        found = true
      end 
      found
    end
end
Amz::Core::Engine.add_routes do
    # devise_for :amz_user,
    #             class_name: Amz.user_class.to_s,
    #             controllers: { sessions: 'amz/user_sessions',
    #                               registrations: 'amz/user_registrations',
    #                               passwords: 'amz/user_passwords',
    #                               confirmations: 'amz/user_confirmations' },
    #             skip: [:unlocks, :omniauth_callbacks],
    #             path_names: { sign_out: 'logout' },
    #             path_prefix: :user
    # devise_scope :amz_user do
    #   get '/login' => 'user_sessions#new', :as => :login
    #   post '/login' => 'user_sessions#create', :as => :create_new_session
    #   get '/logout' => 'user_sessions#destroy', :as => :logout
    #   get '/signup' => 'user_registrations#new', :as => :signup
    #   post '/signup' => 'user_registrations#create', :as => :registration
    #   get '/password/recover' => 'user_passwords#new', :as => :recover_password
    #   post '/password/recover' => 'user_passwords#create', :as => :reset_password
    #   get '/password/change' => 'user_passwords#edit', :as => :edit_password
    #   post '/password/change' => 'user_passwords#update', :as => :update_password
    #   get '/confirm' => 'user_confirmations#show', :as => :confirmation if Amz::Auth::Config[:confirmable]
    # end
    # resources :users, only: [:update] 
    # resource :account, controller: 'users'
    # resource :profile, controller: 'users', action: :profile
    resources :author, only: [:show]

    
    get '/subscription' => 'subscriptions#new', :as => :subscription 
    get '/unsubscribion/*token' => 'subscriptions#cancel', :as => :unsubscribion

    root to: 'home#index'
    get '/csrf_meta_tags.html', to: 'store#csrf_meta_tags', as: :csrf_meta_tags
    get '/manifest.json', to: 'favicon#manifest', as: :manifest
    get '/browserconfig.xml', to: 'favicon#browserconfig', as: :browserconfig
    get '/cms_sitemap.xml', to: 'sitemap#xml_cms', as: :sitemap_xml_cms
    get '/taxons_sitemap.xml', to: 'sitemap#xml_taxons', as: :sitemap_xml_taxons 
    get '/reviews_sitemap.xml', to: 'sitemap#xml_reviews', as: :sitemap_xml_reviews 
    get '/sitemap.xml', to: 'sitemap#index', as: :sitemap

    get '/redirect', to: 'redirect#index', as: :redirects
    put '/search', to: 'search#processing', as: :searches
    get '/search', to: 'search#popular', as: :popular
    get '/results', to: 'search#show', as: :results 
    get '/tag/*keywords', to: 'tag#show', as: :tag 
    get '/media/*style/*review_id.jpg', to: 'review#media', as: :review_media , constraints: UrlConstraint.new
    get '/media/*style/*scale/*review_id.jpg', to: 'review#media', as: :review_media_crop , constraints: UrlConstraint.new

    get '/api/v1/store', to: 'api/store#index', as: :api_stores 
    get '/api/v1/store/*id', to: 'api/store#show', as: :api_store

    post '/api/v1/product', to: 'api/product#index', as: :api_products 
    post '/api/v1/product/*id', to: 'api/product#show', as: :api_product

    get '/api/v1/review', to: 'api/review#index', as: :api_reviews 
    get '/api/v1/review/*id', to: 'api/review#show', as: :api_review

    get '*cms_id', to: 'cms#show', as: :cms, constraints: UrlConstraint.new
    get '*taxon_id', to: 'taxon#show', as: :taxons, constraints: UrlConstraint.new
    get '*review_id', to: 'review#show', as: :reviews, constraints: UrlConstraint.new 
    get '*unmatched_route', to: 'store#route_not_found', constraints: UrlConstraint.new 
    

end

frontend/app/views/amp/shared/_after_body.html.erb
<%= raw current_store.preferred_foot_code %>  

frontend/app/views/amp/shared/_amp_carousel.html.erb
<div class="carousel">
    <% 
        img =  item[:article].image
        srcset = ""
        if img
            box = img.box("medium")   
            x_scale  = 4.0 / 3.0 
            box = box_scale(box, x_scale)
            srcset = { medium: '430', large:   '600' }.map{ |sty, val|  review_media_crop_url(style: sty, review_id: item[:review].slug, scale: "4x3" ) + " #{val}w" }.join(",\r\n") 
        else
            box = { width: 430, height: 430 }
        end
    %>
    <a href="<%= item[:url] %>"  class="img"> 
        <amp-img class="card-image cover" srcset="<%= srcset %>" src="<%= item[:image] %>" width="<%= box[:width] %>" height="<%= box[:height] %>" alt="<%= item[:name] %>" layout="responsive"></amp-img>
    </a>
    
    <div class="card-top"><a href="<%= item[:taxon_url]%>"><%= item[:taxon]%></a></div>
    <h3 class="card-name"><a href="<%= item[:url]%>"><%= item[:name]%></a></h3> 
    <div class="author"> 
        <a href="<%= item[:author_url] %>"> 
            <span class="author-info">
                <span class="avatar"><amp-img src="<%= item[:author_img]%>" alt="<%= item[:author]%>" width="40" height="40"></amp-img></span>
                <span class="author-name"><%= item[:author] %></span>
            </span> 
        </a> 
        <a href="<%= item[:url] %>"><span class="published-at"><%= item[:published_at] %></span></a>  
    </div> 
</div>
         

frontend/app/views/amp/shared/_analytics.html.erb
<% cache ['analytics-head-v2', current_store] do%>
    <% unless current_store.preferred_google_ga.blank? %>
        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
            
            ga('create', '<%= current_store.preferred_google_ga %>', 'auto', {'useAmpClientId': true} ); 
            // ga('send', 'pageview');  
            
        </script>
        <!-- End Google Analytics -->
    <% end %> 
    <% unless current_store.google_gtag.blank? %>  
        <!-- Global site tag (gtag.js) - Google Analytics 4 -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=<%= current_store.google_gtag %>"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date()); 
            gtag('config', '<%= current_store.google_gtag %>', {'use_amp_client_id': true});
        </script> 
    <% end %>
<% end %>

frontend/app/views/amp/shared/_article_card.html.erb
<div class="card">
    <% 
        img =  item[:article].image
        srcset = ""
        if img 
            box =  img.box("medium")   
            x_scale  = 4.0 / 3.0 
            box = box_scale(box, x_scale)
            srcset = { medium: '430', large:   '600' }.map{ |sty, val|  review_media_crop_url(style: sty, review_id: item[:review].slug, scale: "4x3" ) + " #{val}w" }.join(",\r\n") 
        else
            box = { width: 430, height: 430 }
        end
    %>
    <amp-img class="card-image cover" srcset="<%= srcset %>" src="<%= item[:image] %>" width="<%= box[:width] %>" height="<%= box[:height] %>" alt="<%= item[:name] %>" layout="responsive"></amp-img>
    <div class="card-body">
        <div class="card-top"><a href="<%= item[:taxon_url]%>"><%= item[:taxon]%></a></div>
        <h3 class="card-name"><a href="<%= item[:url]%>"><%= item[:name]%></a></h3>
        <% if show_description %>
            <div class="card-text mb-2">
                <%= sanitize amp_description(item[:description]) %>
            </div>
        <% end %>  
        <div class="card-footer">
            <div class="author">
                <% if item[:author_url] %>
                <a href="<%= item[:author_url] %>"> 
                    <span class="author-info">
                        <span class="avatar"><amp-img src="<%= item[:author_img]%>" alt="<%= item[:author]%>" width="40" height="40"></amp-img></span>
                        <span class="author-name"><%= item[:author] %></span>
                    </span> 
                </a>
                <% end %>
                <a href="<%= item[:url] %>"><span class="published-at"><%= item[:published_at] %></span></a>  
            </div>
        </div> 
    </div>
</div>

frontend/app/views/amp/shared/_block_card.html.erb
 <section>
        <h4><%= item[:name] %></h4> 
        <div class="cms">
            <%= sanitize amp_description(item[:content])%>   
        </div>
</section>

frontend/app/views/amp/shared/_breadcrumbs.html.erb
 <% cache ['breadcrumbs-v3',@taxon,@store_review] do %>
 <%= amz_breadcrumbs(@taxon) %>
 <% end %>

frontend/app/views/amp/shared/_footer.html.erb
<footer id="footer" class="container"> 
    <div class="footer-links">
        <%= sanitize footer_links %> 
         <% cache ['flags_amp', @review, @store_review ] do %>
        <%== flags %>  
        <% end %>
    </div>
    <div class="footer-policy"><%= sanitize footer_policy %></div>
    <div class="copy-right">©<%= current_store.name %></div> 
</footer>  
<button aria-label="Scroll To Top" data-vars-label="Scroll To Top" id="scrollToTopButton" on="tap:header.scrollTo(duration=200)" class="scrollToTop">⌃</button>
<% unless current_store.google_gtm_id.blank? %>
<!-- Google Tag Manager -->
<amp-analytics config="https://www.googletagmanager.com/amp.json?id=<%= current_store.google_gtm_id %>&gtm.url=SOURCE_URL" data-credentials="include">
</amp-analytics>
<% end %>
<amp-animation id="showAnim" layout="nodisplay">
  <script type="application/json">
    {
      "duration": "200ms",
       "fill": "both",
       "iterations": "1",
       "direction": "alternate",
       "animations": [
         {
           "selector": "#scrollToTopButton, #btn-table-of-contents",
           "keyframes": [
             { "opacity": "1", "visibility": "visible" }
           ]
         }
       ]
    }
  </script>
</amp-animation>
<amp-animation id="hideAnim" layout="nodisplay">
  <script type="application/json">
    {
     "duration": "200ms",
       "fill": "both",
       "iterations": "1",
       "direction": "alternate",
       "animations": [
         {
           "selector": "#scrollToTopButton, #btn-table-of-contents",
           "keyframes": [
             { "opacity": "0", "visibility": "hidden" }
           ]
         }
       ]
   }
  </script>
</amp-animation>
<amp-install-serviceworker src="/serviceworker.js"
  data-iframe-src="/serviceworker.html"
  layout="nodisplay">
</amp-install-serviceworker>

frontend/app/views/amp/shared/_head.html.erb
<meta charset="utf-8">
<meta name="amp-google-client-id-api" content="googleanalytics">
<title><%= title %></title> 
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=0">
<% if current_store.preferred_esi %>
<esi:include src="/csrf_meta_tags.html" />
<% else %>
<%= csrf_meta_tags %> 
<% end %>
<% cache [ 'favicon_amp_v1' , current_store] do %>
  <%= link_favicon %>
<% end %>
<%= csp_meta_tag %> 
<%== meta_data_tags %>
<%= canonical_tag(current_store.domain) %> 

<%= render partial: 'amp/shared/amp_style' %>

<link rel="preload" as="script" href="https://cdn.ampproject.org/v0.js">
 
<script async src="https://cdn.ampproject.org/v0.js"></script>  
<script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
<script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
<script async custom-element="amp-position-observer" src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js"></script>
<script async custom-element="amp-animation" src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"></script>
<script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
<script async custom-element="amp-autocomplete" src="https://cdn.ampproject.org/v0/amp-autocomplete-0.1.js"></script>
<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
<script async custom-element="amp-install-serviceworker" src="https://cdn.ampproject.org/v0/amp-install-serviceworker-0.1.js"></script>
<script async custom-element="amp-auto-ads" src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"></script>
<%
  logo_image_large = large_url_image(current_store.logo)
%>
<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@graph": [{
        "@type": ["Person", "Organization"],
        "@id": "<%= origin %>/#person",  
        "name": "<%= current_store.name %>",
        "logo": {
          "@type": "ImageObject",
          "url": "<%= logo_image_large %>"
        },
        "image": {
          "@type": "ImageObject",
          "url": "<%= logo_image_large %>"
        }
      },
      {
        "@type": "WebSite",
        "@id": "<%= origin %>/#website",
        "name": "<%= current_store.name %>",
        "url": "<%= origin %>",
        <% if @body_id == 'home-page' %>
        "potentialAction": {
          "@type": "SearchAction",
          "target": "<%= "#{results_url}?keywords={query}" %>",
          "query-input": "required name=query"
        },
        <% end %>
        "publisher": {
          "@id": "<%= origin %>#person"
        }, 
        "inLanguage": "<%= I18n.locale %>"
      }
      <%= yield :ldjson if content_for? :ldjson %> 
      ]
    }
</script>

<%= yield :head if content_for? :head %> 

frontend/app/views/amp/shared/_header.html.erb
<%= raw current_store.preferred_head_code %>  
<amp-state id="searchUrl">
    <script type="application/json">"<%= searches_path %>?keywords="</script>
</amp-state> 

<div id="marker"><amp-position-observer on="enter:hideAnim.start; exit:showAnim.start" layout="nodisplay"></amp-position-observer></div>
<header id="header">  
    <div class="nav bg-dark">  
        <button aria-label="Menu Trigger" class="header-btn" data-vars-label="Menu Trigger" id="menu" on="tap:sidebar-drawer.toggle">
             <i><span class="bar1"></span><span class="bar2"></span><span class="bar3"></span></i>
        </button>   
        <form target="_top" id="searchForm" class="search-box" autocomplete="off" action="<%= searches_path %>" action-xhr="<%= searches_path %>" method="get" >  
        <amp-autocomplete 
            min-characters="1" 
            on="select:AMP.navigateTo(url=event.valueAsObject.url)" 
            filter="token-prefix" 
            filter-value="alt" 
            src="<%= searches_path %>" 
            [src]="searchUrl" 
            query="keywords"  
             
            submit-on-enter 
            >
            <input   
                aria-label="Search"
                id="search-input" 
                data-allow-initialization 
                name="keywords" 
                type="search" >
                <% cache ['logo-amp-v2', @body_id, current_store] do %> 
                        <% if @body_id == "home-page"%>
                            <h1 class="navbar-brand"><a  href="/"><%= mini_image(current_store.logo, alt: current_store.name , width: 168, height: 20, layout: "fixed" ) %><strong><%= current_store.name %></strong></a></h1>
                        <% else %>
                            <a class="navbar-brand" href="/"><%= mini_image(current_store.logo, alt: current_store.name , width: 168, height: 20, layout: "fixed"  ) %></a>
                        <% end %> 
                <% end %> 
                <button aria-label="Search Submit" data-vars-label="Search Submit" class="header-btn search-btn"><%=  svg(:search) %></button>  
                <template type="amp-mustache"  class="results"> 
                    <div data-value="{{alt}}" data-json="{{objToJson}}" class="result-item">
                        <div class="search-item b-bottom">
                            <a href="{{url}}" class="item-result"><amp-img class="layout-fixed" layout="fixed" src="{{image}}" width="80" height="80"></amp-img><span class="item-name"><b>{{{name}}}</b><i>{{title}}</i></span></a>
                        </div>
                    </div>
                </template>   
            </amp-autocomplete>
        </form>   
    </div>   
</header> 
<amp-sidebar id="sidebar-drawer" layout="nodisplay" side="left"> 
    <nav>
        <%= sanitize drawer %>
    </nav>
</amp-sidebar>
<%= yield :header if content_for? :header %>

frontend/app/views/amp/shared/_sidebar.html.erb
<aside id="target-element-desktop" class="desktop-sidebar -tw"></aside>  
<amp-sidebar id="sidebar-desktop" class="desktop-sidebar" layout="nodisplay" side="left"> 
    
    <nav toolbar="(min-width: 1024px)" toolbar-target="target-element-desktop">
        <ul>
        <li>
            <div class="table-of-contents"><%=I18n.t('amz.views.table_of_contents', default: "Table of contents")%></div>
            <input aria-label="<%=I18n.t('amz.views.table_of_contents', default: "Table of contents")%>" data-vars-label="Table of Contents Nav Trigger" class="nav-trigger" type="checkbox">
            <div class="nav"><%= yield :sidebar %></div>
            <i><span class="bar1"></span><span class="bar2"></span><span class="bar3"></span></i>
        </li>
        </ul>
    </nav>
    
</amp-sidebar>

frontend/app/views/amp/shared/_sidebar_right.html.erb
<div class="sidebar-right-desktop">
    <div class="sidebar-innner">
        <%= yield :sidebar_right %>
    </div>
</div> 

frontend/app/views/amp/shared/_social-share.html.erb
<% content_for :head do  %>   
<script async custom-element="amp-social-share" src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"></script>
<% end %>

<div class="social-share">
    <button aria-label="Social Share" class="btn rounded" type="button" data-vars-label="Share Trigger" id="btn-social-share" on="tap:amp-social-share.toggle"><%= svg :share, width: 20, height: 20 %> </button> 
    <div class="amp-social-share" id="amp-social-share">  
        <amp-social-share class="rounded" width="30" height="30" type="facebook" data-vars-label="Share Facebook" aria-label="Share on Facebook" data-param-app_id="<%= current_store.preferred_facebook_app_id %>"></amp-social-share>
        <amp-social-share class="rounded" width="30" height="30" type="linkedin" data-vars-label="Share Linkedin" aria-label="Share on LinkedIn"></amp-social-share>
        <amp-social-share class="rounded" width="30" height="30" type="pinterest"  data-vars-label="Share Pinterest" aria-label="Share on Pinterest" data-param-media="https://amp.dev/static/samples/img/amp.jpg"></amp-social-share>
        <amp-social-share class="rounded" width="30" height="30" type="twitter" data-vars-label="Share Twitter" aria-label="Share on Twitter"></amp-social-share>
        <amp-social-share class="rounded" width="30" height="30" type="whatsapp" data-vars-label="Share Whatsapp" aria-label="Share on WhatsApp"></amp-social-share>
        <amp-social-share class="rounded" width="30" height="30" type="line" data-vars-label="Share Line" aria-label="Share on Line"></amp-social-share> 
        <amp-social-share class="rounded" width="30" height="30" type="system" data-vars-label="Share System" aria-label="Share"></amp-social-share>
    </div>
 </div>

frontend/app/views/amp/shared/_taxon_list.html.erb
<ul class="list-group mb-3">
<li class="list-group-item">
    <a href="<%= item[:url] %>"> <span><%= item[:name] %></span></a> 
</li> 
<li class="list-group-item">
    <a href="<%= item[:url] %>"> 
        <amp-img class="cover"  src="<%= item[:image] %>" alt="<%= item[:name] %>" width="600" height="350" layout="responsive"></amp-img>
    </a> 
</li> 
<% if item[:children].any? %> 
    <% item[:children].each do |children| %> 
    <li class="list-group-item"><a href="<%= children[:url] %>"><span><%= children[:name] %></span></a></li> 
    <% end %> 
<% end %>   
</ul>